In [1]:
import tensorflow as tf
import numpy as np
from skimage import io, transform
import pickle
import os
import numpy as np
import sklearn.preprocessing
############################################################################################################
# Convolution layer Methods
def __conv2d_p(name, x, w=None, num_filters=16, kernel_size=(3, 3), padding='SAME', stride=(1, 1),
               initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0, bias=0.0):
    """
    Convolution 2D Wrapper
    :param name: (string) The name scope provided by the upper tf.name_scope('name') as scope.
    :param x: (tf.tensor) The input to the layer (N, H, W, C).
    :param w: (tf.tensor) pretrained weights (if None, it means no pretrained weights)
    :param num_filters: (integer) No. of filters (This is the output depth)
    :param kernel_size: (integer tuple) The size of the convolving kernel.
    :param padding: (string) The amount of padding required.
    :param stride: (integer tuple) The stride required.
    :param initializer: (tf.contrib initializer) The initialization scheme, He et al. normal or Xavier normal are recommended.
    :param l2_strength:(weight decay) (float) L2 regularization parameter.
    :param bias: (float) Amount of bias. (if not float, it means pretrained bias)
    :return out: The output of the layer. (N, H', W', num_filters)
    """
    with tf.variable_scope(name):
        stride = [1, stride[0], stride[1], 1]
        kernel_shape = [kernel_size[0], kernel_size[1], x.shape[-1], num_filters]

        with tf.name_scope('layer_weights'):
            if w == None:
                w = __variable_with_weight_decay(kernel_shape, initializer, l2_strength)
            __variable_summaries(w)
        with tf.name_scope('layer_biases'):
            if isinstance(bias, float):
                bias = tf.get_variable('biases', [num_filters], initializer=tf.constant_initializer(bias))
            __variable_summaries(bias)
        with tf.name_scope('layer_conv2d'):
            conv = tf.nn.conv2d(x, w, stride, padding)
            out = tf.nn.bias_add(conv, bias)

    return out


def conv2d(name, x, w=None, num_filters=16, kernel_size=(3, 3), padding='SAME', stride=(1, 1),
           initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0, bias=0.0,
           activation=None, batchnorm_enabled=False, max_pool_enabled=False, dropout_keep_prob=-1,
           is_training=True):
    """
    This block is responsible for a convolution 2D layer followed by optional (non-linearity, dropout, max-pooling).
    Note that: "is_training" should be passed by a correct value based on being in either training or testing.
    :param name: (string) The name scope provided by the upper tf.name_scope('name') as scope.
    :param x: (tf.tensor) The input to the layer (N, H, W, C).
    :param num_filters: (integer) No. of filters (This is the output depth)
    :param kernel_size: (integer tuple) The size of the convolving kernel.
    :param padding: (string) The amount of padding required.
    :param stride: (integer tuple) The stride required.
    :param initializer: (tf.contrib initializer) The initialization scheme, He et al. normal or Xavier normal are recommended.
    :param l2_strength:(weight decay) (float) L2 regularization parameter.
    :param bias: (float) Amount of bias.
    :param activation: (tf.graph operator) The activation function applied after the convolution operation. If None, linear is applied.
    :param batchnorm_enabled: (boolean) for enabling batch normalization.
    :param max_pool_enabled:  (boolean) for enabling max-pooling 2x2 to decrease width and height by a factor of 2.
    :param dropout_keep_prob: (float) for the probability of keeping neurons. If equals -1, it means no dropout
    :param is_training: (boolean) to diff. between training and testing (important for batch normalization and dropout)
    :return: The output tensor of the layer (N, H', W', C').
    """
    with tf.variable_scope(name) as scope:
        conv_o_b = __conv2d_p(scope, x=x, w=w, num_filters=num_filters, kernel_size=kernel_size, stride=stride,
                              padding=padding,
                              initializer=initializer, l2_strength=l2_strength, bias=bias)

        if batchnorm_enabled:
            conv_o_bn = tf.layers.batch_normalization(conv_o_b, training=is_training)
            if not activation:
                conv_a = conv_o_bn
            else:
                conv_a = activation(conv_o_bn)
        else:
            if not activation:
                conv_a = conv_o_b
            else:
                conv_a = activation(conv_o_b)

        def dropout_with_keep():
            return tf.nn.dropout(conv_a, dropout_keep_prob)

        def dropout_no_keep():
            return tf.nn.dropout(conv_a, 1.0)

        if dropout_keep_prob != -1:
            conv_o_dr = tf.cond(is_training, dropout_with_keep, dropout_no_keep)
        else:
            conv_o_dr = conv_a

        conv_o = conv_o_dr
        if max_pool_enabled:
            conv_o = max_pool_2d(conv_o_dr)

    return conv_o


def __depthwise_conv2d_p(name, x, w=None, kernel_size=(3, 3), padding='SAME', stride=(1, 1),
                         initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0, bias=0.0):
    with tf.variable_scope(name):
        stride = [1, stride[0], stride[1], 1]
        kernel_shape = [kernel_size[0], kernel_size[1], x.shape[-1], 1]

        with tf.name_scope('layer_weights'):
            if w is None:
                w = __variable_with_weight_decay(kernel_shape, initializer, l2_strength)
            __variable_summaries(w)
        with tf.name_scope('layer_biases'):
            if isinstance(bias, float):
                bias = tf.get_variable('biases', [x.shape[-1]], initializer=tf.constant_initializer(bias))
            __variable_summaries(bias)
        with tf.name_scope('layer_conv2d'):
            conv = tf.nn.depthwise_conv2d(x, w, stride, padding)
            out = tf.nn.bias_add(conv, bias)

    return out


def depthwise_conv2d(name, x, w=None, kernel_size=(3, 3), padding='SAME', stride=(1, 1),
                     initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0, bias=0.0, activation=None,
                     batchnorm_enabled=False, is_training=True):
    """Implementation of depthwise 2D convolution wrapper"""
    with tf.variable_scope(name) as scope:
        conv_o_b = __depthwise_conv2d_p(name=scope, x=x, w=w, kernel_size=kernel_size, padding=padding,
                                        stride=stride, initializer=initializer, l2_strength=l2_strength, bias=bias)

        if batchnorm_enabled:
            conv_o_bn = tf.layers.batch_normalization(conv_o_b, training=is_training)
            if not activation:
                conv_a = conv_o_bn
            else:
                conv_a = activation(conv_o_bn)
        else:
            if not activation:
                conv_a = conv_o_b
            else:
                conv_a = activation(conv_o_b)
    return conv_a


def depthwise_separable_conv2d(name, x, w_depthwise=None, w_pointwise=None, width_multiplier=1.0, num_filters=16,
                               kernel_size=(3, 3),
                               padding='SAME', stride=(1, 1),
                               initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0, biases=(0.0, 0.0),
                               activation=None, batchnorm_enabled=True,
                               is_training=True):
    """Implementation of depthwise separable 2D convolution operator as in MobileNet paper"""
    total_num_filters = int(round(num_filters * width_multiplier))
    with tf.variable_scope(name) as scope:
        conv_a = depthwise_conv2d('depthwise', x=x, w=w_depthwise, kernel_size=kernel_size, padding=padding,
                                  stride=stride,
                                  initializer=initializer, l2_strength=l2_strength, bias=biases[0],
                                  activation=activation,
                                  batchnorm_enabled=batchnorm_enabled, is_training=is_training)

        conv_o = conv2d('pointwise', x=conv_a, w=w_pointwise, num_filters=total_num_filters, kernel_size=(1, 1),
                        initializer=initializer, l2_strength=l2_strength, bias=biases[1], activation=activation,
                        batchnorm_enabled=batchnorm_enabled, is_training=is_training)

    return conv_a, conv_o


############################################################################################################
# Fully Connected layer Methods

def __dense_p(name, x, w=None, output_dim=128, initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0,
              bias=0.0):
    """
    Fully connected layer
    :param name: (string) The name scope provided by the upper tf.name_scope('name') as scope.
    :param x: (tf.tensor) The input to the layer (N, D).
    :param output_dim: (integer) It specifies H, the output second dimension of the fully connected layer [ie:(N, H)]
    :param initializer: (tf.contrib initializer) The initialization scheme, He et al. normal or Xavier normal are recommended.
    :param l2_strength:(weight decay) (float) L2 regularization parameter.
    :param bias: (float) Amount of bias. (if not float, it means pretrained bias)
    :return out: The output of the layer. (N, H)
    """
    n_in = x.get_shape()[-1].value
    with tf.variable_scope(name):
        if w == None:
            w = __variable_with_weight_decay([n_in, output_dim], initializer, l2_strength)
        __variable_summaries(w)
        if isinstance(bias, float):
            bias = tf.get_variable("layer_biases", [output_dim], tf.float32, tf.constant_initializer(bias))
        __variable_summaries(bias)
        output = tf.nn.bias_add(tf.matmul(x, w), bias)
        return output


def dense(name, x, w=None, output_dim=128, initializer=tf.contrib.layers.xavier_initializer(), l2_strength=0.0,
          bias=0.0,
          activation=None, batchnorm_enabled=False, dropout_keep_prob=-1,
          is_training=True
          ):
    """
    This block is responsible for a fully connected followed by optional (non-linearity, dropout, max-pooling).
    Note that: "is_training" should be passed by a correct value based on being in either training or testing.
    :param name: (string) The name scope provided by the upper tf.name_scope('name') as scope.
    :param x: (tf.tensor) The input to the layer (N, D).
    :param output_dim: (integer) It specifies H, the output second dimension of the fully connected layer [ie:(N, H)]
    :param initializer: (tf.contrib initializer) The initialization scheme, He et al. normal or Xavier normal are recommended.
    :param l2_strength:(weight decay) (float) L2 regularization parameter.
    :param bias: (float) Amount of bias.
    :param activation: (tf.graph operator) The activation function applied after the convolution operation. If None, linear is applied.
    :param batchnorm_enabled: (boolean) for enabling batch normalization.
    :param dropout_keep_prob: (float) for the probability of keeping neurons. If equals -1, it means no dropout
    :param is_training: (boolean) to diff. between training and testing (important for batch normalization and dropout)
    :return out: The output of the layer. (N, H)
    """
    with tf.variable_scope(name) as scope:
        dense_o_b = __dense_p(name=scope, x=x, w=w, output_dim=output_dim, initializer=initializer,
                              l2_strength=l2_strength,
                              bias=bias)

        if batchnorm_enabled:
            dense_o_bn = tf.layers.batch_normalization(dense_o_b, training=is_training)
            if not activation:
                dense_a = dense_o_bn
            else:
                dense_a = activation(dense_o_bn)
        else:
            if not activation:
                dense_a = dense_o_b
            else:
                dense_a = activation(dense_o_b)

        def dropout_with_keep():
            return tf.nn.dropout(dense_a, dropout_keep_prob)

        def dropout_no_keep():
            return tf.nn.dropout(dense_a, 1.0)

        if dropout_keep_prob != -1:
            dense_o_dr = tf.cond(is_training, dropout_with_keep, dropout_no_keep)
        else:
            dense_o_dr = dense_a

        dense_o = dense_o_dr
    return dense_o


def dropout(x, dropout_keep_prob, is_training):
    """Dropout special layer"""

    def dropout_with_keep():
        return tf.nn.dropout(x, dropout_keep_prob)

    def dropout_no_keep():
        return tf.nn.dropout(x, 1.0)

    if dropout_keep_prob != -1:
        output = tf.cond(is_training, dropout_with_keep, dropout_no_keep)
    else:
        output = x
    return output


def flatten(x):
    """
    Flatten a (N,H,W,C) input into (N,D) output. Used for fully connected layers after conolution layers
    :param x: (tf.tensor) representing input
    :return: flattened output
    """
    all_dims_exc_first = np.prod([v.value for v in x.get_shape()[1:]])
    o = tf.reshape(x, [-1, all_dims_exc_first])
    return o


############################################################################################################
# Pooling Methods

def max_pool_2d(x, size=(2, 2), stride=(2, 2), name='pooling'):
    """
    Max pooling 2D Wrapper
    :param x: (tf.tensor) The input to the layer (N,H,W,C).
    :param size: (tuple) This specifies the size of the filter as well as the stride.
    :param stride: (tuple) specifies the stride of pooling.
    :param name: (string) Scope name.
    :return: The output is the same input but halfed in both width and height (N,H/2,W/2,C).
    """
    size_x, size_y = size
    stride_x, stride_y = stride
    return tf.nn.max_pool(x, ksize=[1, size_x, size_y, 1], strides=[1, stride_x, stride_y, 1], padding='VALID',
                          name=name)


def avg_pool_2d(x, size=(2, 2), stride=(2, 2), name='avg_pooling'):
    """
        Average pooling 2D Wrapper
        :param x: (tf.tensor) The input to the layer (N,H,W,C).
        :param size: (tuple) This specifies the size of the filter as well as the stride.
        :param name: (string) Scope name.
        :return: The output is the same input but halfed in both width and height (N,H/2,W/2,C).
    """
    size_x, size_y = size
    stride_x, stride_y = stride
    return tf.nn.avg_pool(x, ksize=[1, size_x, size_y, 1], strides=[1, stride_x, stride_y, 1], padding='VALID',
                          name=name)


############################################################################################################
# Utilities for layers

def __variable_with_weight_decay(kernel_shape, initializer, wd):
    """
    Create a variable with L2 Regularization (Weight Decay)
    :param kernel_shape: the size of the convolving weight kernel.
    :param initializer: The initialization scheme, He et al. normal or Xavier normal are recommended.
    :param wd:(weight decay) L2 regularization parameter.
    :return: The weights of the kernel initialized. The L2 loss is added to the loss collection.
    """
    w = tf.get_variable('weights', kernel_shape, tf.float32, initializer=initializer)

    collection_name = tf.GraphKeys.REGULARIZATION_LOSSES
    if wd and (not tf.get_variable_scope().reuse):
        weight_decay = tf.multiply(tf.nn.l2_loss(w), wd, name='w_loss')
        tf.add_to_collection(collection_name, weight_decay)
    return w


# Summaries for variables
def __variable_summaries(var):
    """
    Attach a lot of summaries to a Tensor (for TensorBoard visualization).
    :param var: variable to be summarized
    :return: None
    """
    with tf.name_scope('summaries'):
        mean = tf.reduce_mean(var)
        tf.summary.scalar('mean', mean)
        with tf.name_scope('stddev'):
            stddev = tf.sqrt(tf.reduce_mean(tf.square(var - mean)))
        tf.summary.scalar('stddev', stddev)
        tf.summary.scalar('max', tf.reduce_max(var))
        tf.summary.scalar('min', tf.reduce_min(var))
        tf.summary.histogram('histogram', var)

D:\Python\anaconda3.4\envs\py36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def load_obj(name):
    with open(name, 'rb') as f:
        return pickle.load(f)


def save_obj(obj, name):
    with open(name, 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

In [3]:
#外部参数
experiment_dir = "test_experiment"
num_epochs = 100
num_classes = 1001
batch_size = 1
width_multiplier = 1.0
shuffle = True
l2_strength = 4e-5
bias = np.float64(0)
learning_rate = 1e-3
batchnorm_enabled = True
dropout_keep_prob = 0.999
pretrained_path = "pretrained_weights/mobilenet_v1.pkl"
max_to_keep = 4
save_model_every = 5
test_every = 5
to_train = True
to_test = False

In [4]:
# init parameters and input
X = None
y = None
logits = None
is_training = None
loss = None
regularization_loss = None
cross_entropy_loss = None
train_op = None
accuracy = None
y_out_argmax = None
summaries_merged = None
# mean_img = None
nodes = dict()

pretrained_path = os.path.realpath(pretrained_path)

In [5]:
# 数据集地址  最后的斜杆一定不要漏
path = 'D:/QIN/Face-classfication/TestDatabase_1/'
# 处理后的数据集
path_normalization = 'D:/QIN/Face-classfication/TestDatabase_2/'
# 模型保存地址
model_path = './人脸识别/model.ckpt'
# tfrecord文件存放路径
TFRECORD_FILE = "./人脸识别/tfrecords/"

#全局one-hot编码空间
label_binarizer = ""


In [6]:
def read_img(path):
    map_path, map_relative = [path +x for x in os.listdir(path) if os.path.isfile(path + x) ], [y for y in os.listdir(path)]
    return map_path, map_relative

In [7]:
#默认按列归一化
def def_normalization(x,h = 1):
    # 记录归一化全局最大值最小值，回代时需要
    if h==1:
        #按列归一化
        amin, amax = np.min(x, 0), np.max(x, 0)
        xx = (x - amin) / (amax - amin)
    else:
        #按行归一化
        amin, amax = np.min(x, 1), np.max(x, 1)
        xx = ((x.T - amin) / (amax - amin)).T
    #记录归一化最大值最小值，回代时需要
    return xx

#使用one-hot编码，将离散特征的取值扩展到了欧式空间
def def_one_hot(x):
    if label_binarizer == "":
        binarizer = sklearn.preprocessing.LabelBinarizer()
    else:
        binarizer = label_binarizer
    binarizer.fit(x)
    y= binarizer.transform(x)
    return y

In [8]:
# 读取处理后的图片，顺序打乱，划分测试和训练
def read_new_img(path):
    map_path, map_relative = read_img(path)
    imgs=[]
    labels=[]
    for idx, folder, in enumerate(map_path):
        if map_relative[idx].split(".")[0] == 'train' or map_relative[idx].split(".")[0] == 'test':
            continue
        img = io.imread(path_normalization+map_relative[idx])
        img = transform.resize(img, (224, 224))
        imgs.append(img)
        if map_relative[idx].split(".")[0].split("_")[1].isdigit():
            la_name = map_relative[idx].split(".")[0].split("_")[0]
            labels.append(la_name)
        else:
            la_name = map_relative[idx].split(".")[0].split("_")[0] + '_'+map_relative[idx].split(".")[0].split("_")[1]
            labels.append(la_name)
    x_data, x_label = np.array(imgs), np.array(def_one_hot(np.array(labels)))
    data = []
    sigle_data = []
    for i in range(len(x_data)):
        sigle_data.append(x_data[i])
        sigle_data.append(x_label[i])
        data.append(sigle_data)
        sigle_data = []
        # 打乱顺序
    data = np.array(data)
    num_example = data.shape[0]
    np.random.shuffle(data)
    # 将所有数据分为训练集和验证集
    ratio = 0.8
    img_train = []
    label_train = []
    img_test = []
    label_test = []
    for i in range(int(ratio*num_example)):
        img_train.append(data[i][0])
        label_train.append(data[i][1])
    img_train = np.array(img_train)
    label_train = np.array(label_train)
    for i in range(int(ratio*num_example),num_example):
        img_test.append(data[i][0])
        label_test.append(data[i][1])
    img_test = np.array(img_test)
    label_test = np.array(label_test)
    print(img_train)
    return img_train,img_test,label_train,label_test

In [9]:
def __init_global_epoch():
    """
    Create a global epoch tensor to totally save the process of the training
    :return:
    """
    with tf.variable_scope('global_epoch'):
        global_epoch_tensor = tf.Variable(-1, trainable=False, name='global_epoch')
        global_epoch_input = tf.placeholder('int32', None, name='global_epoch_input')
        global_epoch_assign_op = global_epoch_tensor.assign(global_epoch_input)

In [10]:
def __init_global_step():
    """
    Create a global step variable to be a reference to the number of iterations
    :return:
    """
    with tf.variable_scope('global_step'):
        global_step_tensor = tf.Variable(0, trainable=False, name='global_step')
        global_step_input = tf.placeholder('int32', None, name='global_step_input')
        global_step_assign_op = global_step_tensor.assign(global_step_input)

In [11]:
def __init_mean():
    # Preparing the mean image.
    img_mean = np.ones((1, 224, 224, 3))
    img_mean[:, :, :, 0] *= 103.939
    img_mean[:, :, :, 1] *= 116.779
    img_mean[:, :, :, 2] *= 123.68
    mean_img = tf.constant(img_mean, dtype=tf.float32)

In [12]:
def __init_input():
    with tf.variable_scope('input'):
        # Input images
        X = tf.placeholder(tf.float32,
                                [None, 224, 224,3])
        # Classification supervision, it's an argmax. Feel free to change it to one-hot,
        # but don't forget to change the loss from sparse as well
        y = tf.placeholder(tf.float32, [None,num_classes])   ### <---------------------------注意一下
        # is_training is for batch normalization and dropout, if they exist
        is_training = tf.placeholder(tf.bool)
        # 改变x的格式转为4D的向量[batch, in_height, in_width, in_channels]`
        X = tf.reshape(X, [-1, 224, 224, 3], name='x_image')

In [13]:
def __add_to_nodes(nodes):
    for node in nodes:
        nodes[node.name] = node

In [14]:
def __init_network():
    x_train, x_test, y_train, y_test = read_new_img(path_normalization)
    m,n = y_train.shape
    print("m:")
    print(m)
    print("n:")
    print(n)
    num_classes = n
    with tf.variable_scope('global_epoch'):
        global_epoch_tensor = tf.Variable(-1, trainable=False, name='global_epoch')
        global_epoch_input = tf.placeholder('int32', None, name='global_epoch_input')
        global_epoch_assign_op = global_epoch_tensor.assign(global_epoch_input)
    with tf.variable_scope('global_step'):
        global_step_tensor = tf.Variable(0, trainable=False, name='global_step')
        global_step_input = tf.placeholder('int32', None, name='global_step_input')
        global_step_assign_op = global_step_tensor.assign(global_step_input)

    with tf.variable_scope('input'):
        # Input images
        X = tf.placeholder(tf.float32,
                                [None, 224, 224,3])
        # Classification supervision, it's an argmax. Feel free to change it to one-hot,
        # but don't forget to change the loss from sparse as well
        y = tf.placeholder(tf.float32, [None,num_classes])   ### <---------------------------注意一下
        # is_training is for batch normalization and dropout, if they exist
        is_training = tf.placeholder(tf.bool)
        # 改变x的格式转为4D的向量[batch, in_height, in_width, in_channels]`
        X = tf.reshape(X, [-1, 224, 224, 3], name='x_image')
    with tf.variable_scope('mobilenet_encoder'):
        # Preprocessing as done in the paper
        with tf.name_scope('pre_processing'):
            # Preparing the mean image.
#             img_mean = np.ones((1, 224, 224, 3))
#             img_mean[:, :, :, 0] *= 103.939
#             img_mean[:, :, :, 1] *= 116.779
#             img_mean[:, :, :, 2] *= 123.68
#             mean_img = tf.constant(img_mean, dtype=tf.float32)
#             preprocessed_input = (X - mean_img) / 255.0
            preprocessed_input = tf.cast(X,dtype=tf.float32)
        # Model is here!
        preprocessed_input = tf.cast(X,dtype=tf.float32)
        print(preprocessed_input)
        conv1_1 = conv2d('conv_1', preprocessed_input, num_filters=int(round(32 * width_multiplier)),
                             kernel_size=(3, 3),
                             padding='SAME', stride=(2, 2), activation=tf.nn.relu6,
                             batchnorm_enabled=batchnorm_enabled,
                             is_training=is_training, l2_strength=l2_strength, bias=bias)
#         __add_to_nodes([conv1_1])
        ############################################################################################
        print(conv1_1)
        conv2_1_dw, conv2_1_pw = depthwise_separable_conv2d('conv_ds_2', conv1_1,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=64, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv2_1_dw, conv2_1_pw])
        print(conv2_1_pw)
        conv2_2_dw, conv2_2_pw = depthwise_separable_conv2d('conv_ds_3', conv2_1_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=128, kernel_size=(3, 3), padding='SAME',
                                                                stride=(2, 2),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv2_2_dw, conv2_2_pw])
        print(conv2_2_pw)
        ############################################################################################
        conv3_1_dw, conv3_1_pw = depthwise_separable_conv2d('conv_ds_4', conv2_2_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=128, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv3_1_dw, conv3_1_pw])
        print(conv3_1_pw)
        conv3_2_dw, conv3_2_pw = depthwise_separable_conv2d('conv_ds_5', conv3_1_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=256, kernel_size=(3, 3), padding='SAME',
                                                                stride=(2, 2),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv3_2_dw, conv3_2_pw])
        print(conv3_2_pw)
        ############################################################################################
        conv4_1_dw, conv4_1_pw = depthwise_separable_conv2d('conv_ds_6', conv3_2_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=256, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv4_1_dw, conv4_1_pw])
        print(conv4_1_pw)
        conv4_2_dw, conv4_2_pw = depthwise_separable_conv2d('conv_ds_7', conv4_1_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=512, kernel_size=(3, 3), padding='SAME',
                                                                stride=(2, 2),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv4_2_dw, conv4_2_pw])
        print(conv4_2_pw)
        ############################################################################################
        conv5_1_dw, conv5_1_pw = depthwise_separable_conv2d('conv_ds_8', conv4_2_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=512, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv5_1_dw, conv5_1_pw])
        print(conv5_1_pw)
        conv5_2_dw, conv5_2_pw = depthwise_separable_conv2d('conv_ds_9', conv5_1_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=512, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv5_2_dw, conv5_2_pw])
        print(conv5_2_pw)
        conv5_3_dw, conv5_3_pw = depthwise_separable_conv2d('conv_ds_10', conv5_2_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=512, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv5_3_dw, conv5_3_pw])
        print(conv5_3_pw)
        conv5_4_dw, conv5_4_pw = depthwise_separable_conv2d('conv_ds_11', conv5_3_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=512, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv5_4_dw, conv5_4_pw])
        print(conv5_4_pw)
        conv5_5_dw, conv5_5_pw = depthwise_separable_conv2d('conv_ds_12', conv5_4_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=512, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv5_5_dw, conv5_5_pw])
        print(conv5_5_pw)
        conv5_6_dw, conv5_6_pw = depthwise_separable_conv2d('conv_ds_13', conv5_5_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=1024, kernel_size=(3, 3), padding='SAME',
                                                                stride=(2, 2),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv5_6_dw, conv5_6_pw])
        print(conv5_6_pw)
        ############################################################################################
        conv6_1_dw, conv6_1_pw = depthwise_separable_conv2d('conv_ds_14', conv5_6_pw,
                                                                width_multiplier=width_multiplier,
                                                                num_filters=1024, kernel_size=(3, 3), padding='SAME',
                                                                stride=(1, 1),
                                                                batchnorm_enabled=batchnorm_enabled,
                                                                activation=tf.nn.relu6,
                                                                is_training=is_training,
                                                                l2_strength=l2_strength,
                                                                biases=(bias, bias))
#         __add_to_nodes([conv6_1_dw, conv6_1_pw])
        print(conv6_1_pw)
        ############################################################################################
        avg_pool = avg_pool_2d(conv6_1_pw, size=(7, 7), stride=(1, 1),name="avg_pool")
        print(avg_pool)
        dropped = tf.nn.dropout(avg_pool, dropout_keep_prob)
        print(dropped)
#         dropped = dropout(avg_pool, 0.999, is_training)
        logits = flatten(conv2d('fc', dropped, kernel_size=(1, 1), num_filters=num_classes,
                                         l2_strength=l2_strength,
                                         bias=bias))
        print(logits)
#         return logits
#         __add_to_nodes([avg_pool, dropped, logits])
    with tf.variable_scope('output'):
        regularization_loss = tf.reduce_sum(tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES))
        cross_entropy_loss = tf.reduce_mean(
            tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=tf.argmax(tf.cast(y, dtype=tf.int32),1), name='loss'))
        loss = regularization_loss + cross_entropy_loss

        # Important for Batch Normalization
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
        with tf.control_dependencies(update_ops):
            train_op = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)
            y_out_argmax = tf.argmax(tf.nn.softmax(logits), axis=-1, output_type=tf.int64)

            accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(tf.cast(y,dtype=tf.int64), -1), y_out_argmax), tf.float32))

        # Summaries needed for TensorBoard
        with tf.name_scope('train-summary-per-iteration'):
            tf.summary.scalar('loss', loss)
            tf.summary.scalar('acc', accuracy)
            summaries_merged = tf.summary.merge_all()
    #保存模型使用环境
    saver = tf.train.Saver()

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        # 创建一个协调器，管理线程
        coord = tf.train.Coordinator()
        # 启动QueueRunner, 此时文件名队列已经进队
        threads = tf.train.start_queue_runners(sess=sess, coord=coord)

        for i in range(20):
            # 训练模型
            sess.run(train_op, feed_dict={X: x_train, y: y_train,is_training:True})

            test_acc = sess.run(accuracy, feed_dict={X: x_test, y: y_test,is_training:True})
            train_acc = sess.run(accuracy, feed_dict={X: x_train, y: y_train,is_training:True})
            print("训练第 " + str(i) + " 次, 训练集准确率= " + str(train_acc) + " , 测试集准确率= " + str(test_acc))

            if test_acc == 1 and train_acc >= 0.95:
                print("准确率完爆了")
                # 保存模型
                saver.save(sess, 'nn/my_net.ckpt')
                break

        # 通知其他线程关闭
        coord.request_stop()
        # 其他所有线程关闭之后，这一函数才能返回
        coord.join(threads)

In [15]:
def __init_output(logits):
    with tf.variable_scope('output'):
        regularization_loss = tf.reduce_sum(tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES))
        cross_entropy_loss = tf.reduce_mean(
            tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=tf.argmax(tf.cast(y, dtype=tf.int32),1), name='loss'))
        loss = regularization_loss + cross_entropy_loss

        # Important for Batch Normalization
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
        with tf.control_dependencies(update_ops):
            train_op = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)
            y_out_argmax = tf.argmax(tf.nn.softmax(logits), axis=-1, output_type=tf.int64)

            accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(tf.cast(y,dtype=tf.int64), -1), y_out_argmax), tf.float32))

        # Summaries needed for TensorBoard
        with tf.name_scope('train-summary-per-iteration'):
            tf.summary.scalar('loss', loss)
            tf.summary.scalar('acc', accuracy)
            summaries_merged = tf.summary.merge_all()

In [16]:
def __train():
    #保存模型使用环境
    saver = tf.train.Saver()

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        # 创建一个协调器，管理线程
        coord = tf.train.Coordinator()
        # 启动QueueRunner, 此时文件名队列已经进队
        threads = tf.train.start_queue_runners(sess=sess, coord=coord)

        for i in range(50):
            # 训练模型
            sess.run(train_op, feed_dict={X: x_train, y: y_train, keep_prob: 0.9})

            test_acc = sess.run(accuracy, feed_dict={X: x_test, y: y_test, keep_prob: 1.0})
            train_acc = sess.run(accuracy, feed_dict={X: x_train, y: y_train, keep_prob: 1.0})
            print("训练第 " + str(i) + " 次, 训练集准确率= " + str(train_acc) + " , 测试集准确率= " + str(test_acc))

            if test_acc == 1 and train_acc >= 0.95:
                print("准确率完爆了")
                # 保存模型
                saver.save(sess, 'nn/my_net.ckpt')
                break

        # 通知其他线程关闭
        coord.request_stop()
        # 其他所有线程关闭之后，这一函数才能返回
        coord.join(threads)

In [17]:
def __build():
#     __init_global_epoch()
#     __init_global_step()
#     __init_mean()
#     __init_input()
#     logits = __init_network()
    __init_network()
#     __init_output(logits)
#     __train

In [18]:
if __name__ == "__main__":
    __build()

D:\Python\anaconda3.4\envs\py36\lib\site-packages\skimage\transform\_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "


[[[[0.30588235 0.3372549  0.28627451]
   [0.30588235 0.3372549  0.28627451]
   [0.30980392 0.34117647 0.29019608]
   ...
   [0.19215686 0.19607843 0.14117647]
   [0.21176471 0.21568627 0.16078431]
   [0.22352941 0.22352941 0.17647059]]

  [[0.30588235 0.3372549  0.28627451]
   [0.30588235 0.3372549  0.28627451]
   [0.30980392 0.34117647 0.29019608]
   ...
   [0.19607843 0.2        0.14509804]
   [0.21176471 0.21568627 0.16078431]
   [0.21960784 0.22352941 0.16862745]]

  [[0.30588235 0.3372549  0.28627451]
   [0.30588235 0.3372549  0.28627451]
   [0.31372549 0.34509804 0.29411765]
   ...
   [0.19607843 0.2        0.14509804]
   [0.21176471 0.21568627 0.16078431]
   [0.21960784 0.22352941 0.16862745]]

  ...

  [[0.87058824 0.87843137 0.85882353]
   [0.87058824 0.87843137 0.85882353]
   [0.8745098  0.87843137 0.85882353]
   ...
   [0.4627451  0.36078431 0.27058824]
   [0.46666667 0.36470588 0.2745098 ]
   [0.47058824 0.36862745 0.27843137]]

  [[0.86666667 0.8745098  0.85490196]
   [0.8